#!/bin/bash

exec 2>&1
set -x

#
# Example event lines in event export
#
#{
#  "metadata": {
#    "name": "environment-management.17875d5c5580a5ef",
#    "namespace": "flux-system",
#    "uid": "9ff2f35c-bc45-49c4-993d-2ab91cdbd5f3",
#    "resourceVersion": "78394894",
#    "creationTimestamp": "2023-09-22T23:47:15Z",
#    "annotations": {
#      "infra.contrib.fluxcd.io/revision": "main@sha1:feaa6533ade779879716c0b7c6b455cc7aec860b"
#    }
#  },
#  "reason": "Progressing",
#  "message": "Apply error: State locked with Lock Identifier 151234d8-a64b-20c5-c4ef-23a61de3d554",
#  "source": {
#    "component": "tf-controller"
#  },
#  "firstTimestamp": "2023-09-22T23:47:15Z",
#  "lastTimestamp": "2023-09-22T23:47:15Z",
#  "count": 1,
#  "type": "Warning",
#  "eventTime": null,
#  "reportingComponent": "",
#  "reportingInstance": "",
#  "clusterName": "",
#  "involvedObject": {
#    "kind": "Terraform",
#    "namespace": "flux-system",
#    "name": "environment-management",
#    "uid": "8b8b6770-3914-4696-adde-0232130e1c06",
#    "apiVersion": "infra.contrib.fluxcd.io/v1alpha2",
#    "resourceVersion": "78390902",
#    "labels": {
#      "kustomize.toolkit.fluxcd.io/name": "cluster-configuration",
#      "kustomize.toolkit.fluxcd.io/namespace": "flux-system"
#    }
#  }
#}
#{
#  "metadata": {
#    "name": "environment-management.17875d6a8accc35a",
#    "namespace": "flux-system",
#    "uid": "32cbc327-63cf-48ad-b088-6d8da204b40c",
#    "resourceVersion": "78395316",
#    "creationTimestamp": "2023-09-22T23:48:16Z",
#    "annotations": {
#      "infra.contrib.fluxcd.io/revision": "main@sha1:feaa6533ade779879716c0b7c6b455cc7aec860b"
#    }
#  },
#  "reason": "Progressing",
#  "message": "Drift detection error: State locked with Lock Identifier 151234d8-a64b-20c5-c4ef-23a61de3d554",
#  "source": {
#    "component": "tf-controller"
#  },
#  "firstTimestamp": "2023-09-22T23:48:16Z",
#  "lastTimestamp": "2023-09-22T23:48:16Z",
#  "count": 1,
#  "type": "Warning",
#  "eventTime": null,
#  "reportingComponent": "",
#  "reportingInstance": "",
#  "clusterName": "",
#  "involvedObject": {
#    "kind": "Terraform",
#    "namespace": "flux-system",
#    "name": "environment-management",
#    "uid": "8b8b6770-3914-4696-adde-0232130e1c06",
#    "apiVersion": "infra.contrib.fluxcd.io/v1alpha2",
#    "resourceVersion": "78394895",
#    "labels": {
#      "kustomize.toolkit.fluxcd.io/name": "cluster-configuration",
#      "kustomize.toolkit.fluxcd.io/namespace": "flux-system"
#    }
#  }
#}

# Determine timestamp that lastTimestamp should be checked for
export TZ=UTC # force all timestamps to be in UTC (+00:00 / Z)
now=$(date +%s)
start_date_epoch=$((now - 5*60))
printf -v start_date_iso8601 '%(%Y-%m-%dT%H:%M:%S+00:00)T' "$start_date_epoch"

# Look up the events in the event exporter pod
EVENT_EXPORTER_POD=$(kubectl get pod -n kube-system -l app=event-exporter -o=name)

LOCKED=$(kubectl logs ${EVENT_EXPORTER_POD} -n kube-system | \
  jq -r '. | select(.message|test(".*State locked with Lock Identifier.*")) | .' | \
  jq -r --arg start_date "$start_date_iso8601" 'select($start_date < .lastTimestamp)| (.message | split(" ")[-1]) + ":" + .involvedObject.name' | \
  sort -u)

for locked in $LOCKED
do
  LOCK_ID=$(echo $locked | cut -f 1 -d ':')
  LOCK_OBJECT=$(echo $locked | cut -f 2 -d ':')

#  AWS DynamoDB should have an entry like this:
#
#        {
#            "LockID": {
#                "S": "faber-terraform-states/faber/management/terraform.tfstate"
#            },
#            "Info": {
#                "S": "{\"ID\":\"96363d54-f7c5-ff10-43b6-8126a88bc3fd\",\"Operation\":\"OperationTypePlan\",\"Info\":\"\",\"Who\":\"Who\":\"runner@environment-management-tf-runner\",\"Version\":\"1.4.6\",\"Created\":\"2023-09-25T07:35:27.755421565Z\",\"Path\":\"faber-terraform-states/faber/management/terraform.tfstate\"}"
#            }
#        },

  # Check who locked the terraform run
  WHO_LOCKED=$(aws dynamodb scan --table-name faber-terraform-locks | jq -r '.Items[] | select(.Info != null) | .Info.S' | jq -r --arg lock_id "$LOCK_ID" 'select(.ID == $lock_id)| .Who')

  LOCKED_BY_RUNNER=$(echo $WHO_LOCKED | grep "^runner@${LOCK_OBJECT}-tf-runner")

  # LOCKED_BY_RUNNER is empty if the lock is hold by a human operator

  if [ -n "${LOCKED_BY_RUNNER}" ]
  then
    kubectl patch terraform ${LOCKED_OBJECT} --type=merge -n flux-system -p '{"spec":{"tfstate": {"forceUnlock":"auto"}}}'
  fi
  
done